# Generated by Django 6.1 on 2026-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='regular_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='owner',
            name='student_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
