# Generated by Django 6.1 on 2026-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='checked_in_at',
            new_name='check_in_time',
        ),
        migrations.AddField(
            model_name='checkin',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='walk_in_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('regular', 'Regular')], max_length=10),
        ),
    ]
