# Generated by Django 6.1 on 2026-08-21 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_code', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('member_type', models.CharField(choices=[('MEMBER', 'Member'), ('PROSPECT', 'Walk-in / prospect')], default='MEMBER', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.gym')),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.location')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('duration_value', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='MONTH', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_day_pass', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.gym')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.member')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='core.membership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.membershipplan')),
            ],
            options={
                'ordering': ['-end_date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'member_type', 'archived_at'], name='core_member_gym_id_7b90ed_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'last_name', 'first_name'], name='core_member_gym_id_5d19b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('member_code', ''), _negated=True), fields=('gym', 'member_code'), name='uniq_member_code_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(fields=('gym', 'name'), name='uniq_plan_name_per_gym'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['gym', 'end_date'], name='core_member_gym_id_ed73e0_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['member', '-end_date'], name='core_member_member__cbd338_idx'),
        ),
    ]
