# Generated by Django 6.1 on 2026-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_membershipplan_membership_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['sort_order', 'category', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='membershipplan',
            name='uniq_plan_name_per_gym',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(fields=('gym', 'name', 'category'), name='uniq_plan_name_per_gym'),
        ),
    ]
