# Generated by Django 6.1 on 2026-08-31 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('MEMBER', 'Member'), ('WALKIN', 'Walk-in')], max_length=10)),
                ('membership_status', models.CharField(blank=True, max_length=20)),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('visitor_name', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, choices=[('regular', 'Regular'), ('student', 'Student')], max_length=10)),
                ('amount_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('checked_in_at', models.DateTimeField()),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.gym')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='core.location')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to='core.member')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['gym', '-checked_in_at'], name='core_checki_gym_id_156e4f_idx'), models.Index(fields=['member', '-checked_in_at'], name='core_checki_member__8c342a_idx')],
            },
        ),
    ]
