# Generated by Django 6.1 on 2026-09-02 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='claim_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='member',
            name='claim_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('claim_code', ''), _negated=True), fields=('gym', 'claim_code'), name='uniq_claim_code_per_gym'),
        ),
    ]
