# Generated by Django 6.1 on 2026-09-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_announcement_event_eventregistration_eventresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', 'time_slot__start_time', 'id']},
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-checked_in_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-end_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['sort_order', 'category', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time', 'label', 'id']},
        ),
    ]
