# Generated by Django 6.1 on 2026-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_announcement_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
