# Generated by Django 6.1 on 2026-09-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_checkin_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='coach_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
