# Generated by Django 6.1 on 2026-09-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_sale_saleitem_stockadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rest_days',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
