# Generated by Django 6.1 on 2026-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_member_rest_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='classes_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
