# Generated by Django 6.1 on 2026-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_last_step',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='qr_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
