# Generated by Django 6.1 on 2026-09-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_devicetoken_notificationsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
