# Generated by Django 6.1 on 2026-09-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_owner_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
